name: MAIN - CI/CD Pipeline (CLIENT)
on:
  push:
    tags:
      - "cv*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build step
        run: |
          echo "Building project..."
          echo "Building client from $(cat client/client.txt)"

  test:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Test step
        run: |
          echo "Running tests..."
          echo "Testing client..."
          echo "Testing server..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy step
        run: |
          echo "Deploying to production..."
          echo "Deploying client..."
          echo "Deploying server..."
